# Generated by Django 3.0.7 on 2020-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="score", name="video_link",),
        migrations.AddField(
            model_name="score",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Link to the Celery task that scored the video.",
                max_length=200,
                null=True,
            ),
        ),
    ]
