# Generated by Django 3.0.7 on 2020-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0003_auto_20200722_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="emotion_score",
            field=models.FloatField(
                blank=True,
                help_text="Tinydoor score for gauging positive customer experience.",
                null=True,
            ),
        ),
    ]
