# Generated by Django 2.2.10 on 2020-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_title', models.CharField(help_text='Name of this analysis.', max_length=200, unique=True)),
                ('image', models.ImageField(help_text='Image being analyzed.', upload_to='tinydoor-client-uploads')),
            ],
        ),
    ]
